aya-rs/book

- src/start/development.md
(Used GitHub UI, not sure what happened to the last line)
> Fix link to rustup

- examples/myapp-01/myapp/src/main.rs
- examples/myapp-02/README.md
- examples/myapp-02/myapp/src/main.rs
- examples/myapp-03/myapp/src/main.rs
> fix myapp-02 example build and run instructions

- examples/myapp-01/myapp/Cargo.toml
- examples/myapp-01/myapp/src/main.rs
- src/start/hello-xdp.md
PR updates the `myapp-01` example and the text in https://aya-rs.github.io/book/start/hello-xdp.html to sync with the code generated by the current aya-template.
> sync myapp-01 example program with aya-template

- examples/aya-gen/myapp-common/Cargo.toml
- examples/aya-gen/myapp-ebpf/Cargo.toml
- examples/aya-gen/myapp/Cargo.toml
- examples/aya-gen/myapp/src/main.rs
- examples/aya-gen/xtask/Cargo.toml
- examples/myapp-01/myapp-common/Cargo.toml
- examples/myapp-01/myapp-ebpf/Cargo.toml
- examples/myapp-01/myapp/Cargo.toml
- examples/myapp-01/myapp/src/main.rs
- examples/myapp-01/xtask/Cargo.toml
- examples/myapp-02/myapp-common/Cargo.toml
- examples/myapp-02/myapp-ebpf/Cargo.toml
- examples/myapp-02/myapp/Cargo.toml
- examples/myapp-02/myapp/src/main.rs
- examples/myapp-02/xtask/Cargo.toml
- examples/myapp-03/myapp-common/Cargo.toml
- examples/myapp-03/myapp-ebpf/Cargo.toml
- examples/myapp-03/myapp/Cargo.toml
- examples/myapp-03/myapp/src/main.rs
- examples/myapp-03/xtask/Cargo.toml
- src/intro/index.md
Use Rust edition 2021 and sync with aya-template change in  https://github.com/aya-rs/aya-template/pull/34.
> use edition 2021

- examples/aya-gen/myapp-ebpf/Cargo.toml
- examples/myapp-01/myapp-ebpf/Cargo.toml
- examples/myapp-02/myapp-ebpf/Cargo.toml
- examples/myapp-02/xtask/Cargo.toml
- examples/myapp-03/myapp-ebpf/Cargo.toml
- examples/myapp-03/xtask/Cargo.toml
- src/start/development.md
- src/start/logging-packets.md
I noticed this when copying examples from the book.
> Ensure urls use https

- src/start/development.md
Point out the need for the latest LLVM version with llvm-sys (currently LLVM 14).  
See the Discord thread around https://discord.com/channels/855676609003651072/934746428700516382/978959310098952212
> need for the latest LLVM version with llvm-sys

- examples/myapp-02/xtask/src/codegen.rs
- examples/myapp-03/xtask/src/codegen.rs
- src/aya/aya-gen.md
- src/programs/lsm.md
Adapt for aya_gen API changes in https://github.com/aya-rs/aya/pull/297.
Fixes #36.
> examples: adapt for changed aya_gen API

- docs/book/start/logging-packets.md
- examples/myapp-02/myapp-ebpf/src/main.rs
- examples/myapp-02/myapp/src/main.rs
- examples/myapp-03/myapp-ebpf/src/main.rs
- examples/myapp-03/myapp/src/main.rs
Signed-off-by: Billy McFall <22157057+Billy99@users.noreply.github.com>
> Fix a couple of nits while running through for first time.

- docs/book/start/development.md
- docs/book/start/dropping-packets.md
- docs/book/start/logging-packets.md
- add bpftool to requirements
- fix the xdp chapter a bit
> misc fixes

- docs/index.md
- mkdocs.yml
Signed-off-by: Dave Tucker <dave@dtucker.co.uk>
> Add Who's Using Aya Section

- README.md
Credit to @vadorovsky https://discord.com/channels/855676609003651072/855676609003651075/1006145022208524298
> add instructions on the local render

- docs/book/programs/lsm.md
> LSM: Add information about ensuring that BPF LSM is enabled

- examples/tc-egress/tc-egress-ebpf/src/main.rs
> tc-egress: Fix the return code

- examples/cgroup-skb-egress/cgroup-skb-egress-ebpf/src/main.rs
- examples/tc-egress/tc-egress-ebpf/src/main.rs
> examples/cgroup-skb: Fix the access to __sk_buff

- docs/book/programs/classifiers.md
It looks like the foldable code comments are not describing what the code is really doing
> fix: Fix code comments

- docs/book/aya/aya-tool.md
- docs/book/programs/lsm.md
- docs/book/programs/probes.md
While reading through the book I spotted this small typo which ended up being on a few different pages.
> chore: fix typo in several pages

- .github/workflows/ci.yml
- examples/aya-tool/myapp-common/Cargo.toml
- examples/aya-tool/myapp-ebpf/rust-toolchain.toml
- examples/aya-tool/myapp/Cargo.toml
- examples/aya-tool/myapp/src/main.rs
- examples/aya-tool/xtask/Cargo.toml
- examples/aya-tool/xtask/src/build_ebpf.rs
- examples/aya-tool/xtask/src/main.rs
- examples/aya-tool/xtask/src/run.rs
- examples/cgroup-skb-egress/cgroup-skb-egress-ebpf/rust-toolchain.toml
- examples/kprobetcp/Cargo.lock
- examples/kprobetcp/kprobetcp-ebpf/rust-toolchain.toml
- examples/lsm-nice/lsm-nice-ebpf/rust-toolchain.toml
- examples/lsm-nice/lsm-nice/Cargo.toml
- examples/lsm-nice/lsm-nice/src/main.rs
- examples/lsm-nice/xtask/Cargo.toml
- examples/lsm-nice/xtask/src/build_ebpf.rs
- examples/lsm-nice/xtask/src/main.rs
- examples/lsm-nice/xtask/src/run.rs
- examples/tc-egress/tc-egress-ebpf/rust-toolchain.toml
- examples/xdp-drop/xdp-drop-ebpf/rust-toolchain.toml
- examples/xdp-hello/xdp-hello-ebpf/rust-toolchain.toml
- examples/xdp-log/xdp-log-ebpf/rust-toolchain.toml
> sync aya-tool example with aya-template

- .github/dependabot.yml
- .github/workflows/ci.yml
- Enable cache before installing bpf-linker
- Add dependabot config
> Add dependabot config

- .github/workflows/ci.yml
- examples/aya-tool/myapp-ebpf/Cargo.toml
- examples/cgroup-skb-egress/cgroup-skb-egress-ebpf/Cargo.toml
- examples/cgroup-skb-egress/xtask/Cargo.toml
- examples/kprobetcp/kprobetcp-ebpf/Cargo.toml
- examples/lsm-nice/lsm-nice-ebpf/Cargo.toml
- examples/tc-egress/tc-egress-ebpf/Cargo.toml
- examples/tc-egress/xtask/Cargo.toml
- examples/xdp-drop/xdp-drop-ebpf/Cargo.toml
- examples/xdp-drop/xtask/Cargo.toml
- examples/xdp-hello/xdp-hello-ebpf/Cargo.toml
- examples/xdp-log/xdp-log-ebpf/Cargo.toml
- examples/xdp-log/xtask/Cargo.toml
- Remove spurious branch = "main"
- Fix rust-cache configuration
> Fix rust-cache configuration

- docs/index.md
Updates the, "Who's using Aya" entry for Exein.
* Fixes broken logo URL
* Updates the, "See more _here_" to direct to the Pulsar repository
> Update who's using aya section

- examples/lsm-nice/lsm-nice/src/main.rs
> bug fix: set global PID in lsm-nice

- docs/index.md
They are not using Aya anymore.
> index: Remove Parca from the list of projects

- docs/index.md
> Update deepfence logo

- .github/workflows/ci.yml
> .github: build on ubuntu-latest

- docs/index.md
bpfd was renamed in Nov 2023 to  bpfman.
> docs: rename bpfd to bpfman

- examples/kprobetcp/kprobetcp/src/main.rs
Thank you for these examples, they are very useful. One of them contained some deprecated names so I updated it.
> Update deprecated names

- docs/book/programs/cgroup-skb.md
- docs/book/programs/lsm.md
Remove it where the output isn't shown.
> Replace # with $ in shell snippets

- docs/book/programs/xdp.md
- examples/cgroup-skb-egress/cgroup-skb-egress/Cargo.toml
- examples/cgroup-skb-egress/cgroup-skb-egress/src/main.rs
- examples/kprobetcp/kprobetcp/Cargo.toml
- examples/kprobetcp/kprobetcp/src/main.rs
- examples/lsm-nice/lsm-nice/src/main.rs
- examples/tc-egress/tc-egress/Cargo.toml
- examples/tc-egress/tc-egress/src/main.rs
- examples/xdp-drop/xdp-drop/Cargo.toml
- examples/xdp-drop/xdp-drop/src/main.rs
- examples/xdp-hello/xdp-hello/Cargo.toml
- examples/xdp-hello/xdp-hello/src/main.rs
- examples/xdp-log/xdp-log/Cargo.toml
- examples/xdp-log/xdp-log/src/main.rs
See https://github.com/aya-rs/aya/commit/35332f2288b0bbb8981233ae464715.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/book/233)
> Adapt to removal of `async_tokio` feature
