src/start/development.md
correct cargo install cargo-generate command
The current command produces the following error:
```
$ cargo install --git http://github.com/cargo-generate/cargo-generate
Updating git repository `http://github.com/cargo-generate/cargo-generate`
error: multiple packages with binaries found: cargo-generate, placeholders. When installing a git repository, cargo will always search the entire repo for any Cargo.toml. Please specify which to install.
```
`cargo install --git http://github.com/cargo-generate/cargo-generate cargo-generate` works fine.
=> src/start: correct cargo install cargo-generate

src/start/development.md
PR shows how to create skeleton aya projects with `cargo generate` in a non-interactive mode by passing parameters to the command. /cc @dave-tucker
=> mention cargo generate param options

src/start/development.md
PR updates the `bpf-linker` commands in https://aya-rs.github.io/book/start/development.html to reflect the `rust-llvm` being now the default and `system-llvm` - an optional feature for the bpf-linker.
=> bpf-linker docs - rust-llvm default feature

src/start/development.md
Dave's changes were already released in 0.9.0[0][1], now there is 0.13.0
released, we are more than fine to just use the latest release.
[0] https://github.com/cargo-generate/cargo-generate/commit/cf12f1d6ba1721a1007999dee90348f6eaa1dca0
[1] https://github.com/cargo-generate/cargo-generate/commit/ef81aefab51f92e695225db65b2248f8b6ace46f
Co-authored-by: Dmitry Savintsev <dsavints@gmail.com>
Signed-off-by: Dmitry Savintsev <dsavints@gmail.com>
=> development: Use the latest release of cargo-generate instead of git

mkdocs.yml
PR moves the "Development Environment" section of the book (currently https://aya-rs.dev/book/start/development/) one level up, to be on the same level and before "A Simple XDP Program".  The Development Environment instructions are relevant not only to the XDP but to any type of Aya program. It would be good to make it "top-level visible" in case someone doesn't think of expanding "A Simple XDP Program".
Signed-off-by: Dmitry Savintsev <dsavints@gmail.com>
=> move Development Environment out of XDP example

docs/book/start/development.md
=> development: Always install bpf-linker from crates, not from git

examples/aya-tool/myapp-ebpf/Cargo.toml, examples/myapp-01/myapp-ebpf/Cargo.toml, examples/myapp-02/myapp-ebpf/Cargo.toml, examples/myapp-03/myapp-ebpf/Cargo.toml, examples/tc-egress/tc-egress-ebpf/Cargo.toml
This crate has been moved from aya-rs/aya-log into the aya repository as of July-ish this year according to the aya-log git history.  Several of the examples in the book were not working as expected (myapp-01 for example was not emitting the format string for ebpf logging macro invocations) so by updating these Cargo.toml deps to point at the new crate version we can get the examples back to working out-of-the-box.
This will also help avoid having potential future users depending on the old/deprecated version of this crate.  I would suggest also adding additional instructions to the old crate's README.
=> Updating aya-rs/aya-log references to aya-rs/aya

docs/book/programs/cgroup-skb.md, docs/book/start/logging-packets.md
The `bindgen` has changed to a workspace member:
https://github.com/rust-lang/rust-bindgen/commits/master/bindgen-cli
Signed-off-by: Eval EXEC <execvy@gmail.com>
=> Fix bindgen installation command

.github/workflows/ci.yml, examples/aya-tool/myapp-ebpf/rust-toolchain.toml, examples/aya-tool/xtask/src/build_ebpf.rs, examples/cgroup-skb-egress/cgroup-skb-egress-ebpf/rust-toolchain.toml, examples/cgroup-skb-egress/xtask/src/build_ebpf.rs, examples/kprobetcp/kprobetcp-ebpf/rust-toolchain.toml, examples/kprobetcp/xtask/src/build_ebpf.rs, examples/lsm-nice/lsm-nice-ebpf/rust-toolchain.toml, examples/lsm-nice/xtask/src/build_ebpf.rs, examples/tc-egress/tc-egress-ebpf/rust-toolchain.toml, examples/tc-egress/xtask/src/build_ebpf.rs, examples/xdp-drop/xdp-drop-ebpf/rust-toolchain.toml, examples/xdp-drop/xtask/src/build_ebpf.rs, examples/xdp-hello/xdp-hello-ebpf/rust-toolchain.toml, examples/xdp-hello/xtask/src/build_ebpf.rs, examples/xdp-log/xdp-log-ebpf/rust-toolchain.toml, examples/xdp-log/xtask/src/build_ebpf.rs
We need to wait for the following fixes in Rust nightly to be able to use the newest one:
* https://github.com/rust-lang/rust/pull/106796
* https://github.com/rust-lang/rust/pull/106856
=> examples: Pin Rust nightly to 2023-01-10

examples/xdp-drop/xdp-drop-ebpf/src/main.rs, examples/xdp-log/xdp-log-ebpf/src/main.rs
The book perfectly [describes](https://github.com/aya-rs/book/blob/main/docs/book/start/dropping-packets.md#populating-our-map-from-userspace) the issue that `u32::from_be()` solves, however the code for it was missing in both `xdp-log` and `xdp-drop` examples.
=> fix network to host endiannes for ipv4

docs/index.md
It occurred to me while glancing at the main page that this link wasn't actually linking in the render, so this patch adds a markdown link in order to fix that.
=> chore: fix link to ebpf.io in index

examples/aya-tool/myapp/Cargo.toml, examples/cgroup-skb-egress/cgroup-skb-egress/Cargo.toml, examples/kprobetcp/kprobetcp/Cargo.toml, examples/lsm-nice/lsm-nice/Cargo.toml, examples/tc-egress/tc-egress/Cargo.toml, examples/xdp-drop/xdp-drop/Cargo.toml, examples/xdp-hello/xdp-hello/Cargo.toml, examples/xdp-log/xdp-log/Cargo.toml
PR updates the tokio dependency to 1.24 in the examples.
=> examples: upgrade tokio dep to 1.24

docs/book/programs/lsm.md
Configuration commands for GRUB might differ depending on GRUB version
or Linux distribution. Mention both of them in the documentation.
Note: Tested on `Linux ubuntu 5.15.0-53-generic #59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
=> lsm: Mention both `upgrade-grub2` and `grub-mkconfig` commands

examples/aya-tool/myapp/Cargo.toml, examples/aya-tool/myapp/src/main.rs
Remove unused structopt dependency - no command-line parameters are expected or needed by this example.
=> remove unused structopt dependency in aya-tool example

examples/aya-tool/myapp-ebpf/src/main.rs, examples/cgroup-skb-egress/cgroup-skb-egress-ebpf/src/main.rs, examples/xdp-drop/xdp-drop-ebpf/src/main.rs
All map types designed to be used for defining maps in eBPF programs are wrapped in `UnsafeCell`, therefore there is no need to declare them as `static mut`.
=> examples: Declare maps as `static` instead of `static mut`

docs/index.md
Companies like Deepfence, Exein and Red Hat are singular entities, hence the verb should be in singular form.
=> index: Use the correct verb ("is" instead of "are") for singular entities

docs/book/aya/crosscompile.md, mkdocs.yml
PR adds cross-compilation instructions for MacOS (Windows still _TODO_), taken from https://github.com/dmitris/tcbpftest/blob/main/README.md#cross-compilation
=> add cross-compilation instructions for MacOS

docs/index.md
This patch adds Kubernetes SIGs as official users of Aya, now that https://github.com/kubernetes-sigs/blixt is an official CNCF project under Kubernetes SIG Network.
=> docs: add kubernetes sigs to who's using Aya

docs/book/aya/crosscompile.md, docs/book/start/development.md
I was following the document and noticed that the command `cargo install bpf-linker --no-default-features` is failing with the following error
```
error: No suitable version of LLVM was found system-wide or pointed
to by LLVM_SYS_180_PREFIX.
Consider using `llvmenv` to compile an appropriate copy of LLVM, and
refer to the llvm-sys documentation for more information.
llvm-sys: https://crates.io/crates/llvm-sys
llvmenv: https://crates.io/crates/llvmenv
--> /Users/cuichli/.cargo/registry/src/index.crates.io-6f17d22bba15001f/llvm-sys-180.0.0/src/lib.rs:515:1
|
515 | / std::compile_error!(concat!(
516 | |     "No suitable version of LLVM was found system-wide or pointed
517 | |        to by LLVM_SYS_",
518 | |     env!("CARGO_PKG_VERSION_MAJOR"),
...   |
525 | |        llvmenv: …
```
=> Update commands used on Mac to set up environment

docs/book/programs/lsm.md
[lsm_hooks.h](https://github.com/torvalds/linux/blob/master/include/linux/lsm_hooks.h) does not appear to actually list the hooks as stated in the original text, rather it contains definitions for a data structure providing the list during execution. I also found the wording to be slightly confusing, as to my understanding, the author of the LSM module is the one making the policy decisions.
If I'm ignorant to something please let me know, it's my first day working with BPF 🐝
=> Link and wording fix: lsm.md

docs/book/programs/xdp.md
Added documentation for https://aya-rs.dev/book/programs/xdp/
Feel free to make reviews and suggest improvements.
=> docs: add Program Types/XDP documentation

docs/book/programs/xdp.md
Fixed a typo error and updated the supported drivers list for native XDP.
Since I'm fetching the list from an external source, it may be better to redirect the users there instead of displaying the table on the aya docs? So that it doesn't need to get updated constantly.
=> fix(program-types/xdp): remove typo and update driver support table

examples/cgroup-skb-egress/xtask/src/main.rs
`generate` is no longer reexported from the root.
=> Update aya_tool reference

.github/dependabot.yml
This should update pyproject.toml, though we still need to update
requirements.txt manually using `uv pip freeze > requirements.txt`.
=> dependabot: add python

.github/dependabot.yml
enable-beta-ecosystems is a top-level key.
=> ci: Fix dependabot.yml

docs/book/start/development.md
bpf-linker installation on debian distro requires additional packages, which only updated in https://github.com/aya-rs/bpf-linker yet to the book.
=> Add necessary package installation info for debian based distro

docs/book/programs/probes.md
While linux kernel code is changing, link to `tcp_connect` symbol is not matched with specific line.
How about change link with search result?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aya-rs/book/241)
=> Fix link to search tcp-connect on elixir for fixed linux version(v6.16.9)
